[pytest]
testpaths = .
markers =
    smoke: mark test as smoke
    regression: mark test as regression
filterwarnings =
    ignore:the matrix subclass is not the recommended way:PendingDeprecationWarning
    ignore::FutureWarning:sklearn
    ignore:X has feature names, but:UserWarning:sklearn
    ignore::RuntimeWarning:statsmodels
    ignore:The number of replications is low:RuntimeWarning:hyppo
    ignore:invalid value encountered in scalar divide:RuntimeWarning:numpy
    ignore:Mean of empty slice:RuntimeWarning:numpy
    ignore:divide by zero encountered in divide:RuntimeWarning:numpy
    ignore:invalid value encountered in multiply:RuntimeWarning:numpy