[metadata]
name = causalexplain
version = attr: causalexplain._version.__version__
description = A package to extract the causal graph from continuous tabular data.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/renero/causalexplain
author = J. Renero
author_email = jesus.renero@gmail.com
license = MIT License
license_files =
classifiers =
    Intended Audience :: Science/Research
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Programming Language :: Python
    Programming Language :: Python :: 3.10
    Topic :: Software Development
    Topic :: Scientific/Engineering
    Operating System :: OS Independent
keywords = causal inference, causal graph, data science

[options]
packages = find:
install_requires =
    causal-learn>=0.1.3.3
    colorama>=0.4.6
    hyppo>=0.4.0
    igraph>=0.11.3
    joblib>=1.3.2
    kneed>=0.8.5
    matplotlib>=3.10.0
    mlforge
    networkx>=3.4.2
    nicegui>=1.4.0
    numpy>=1.21.0
    optuna>=3.3.0
    pandas>=2.2.3
    pydot>=1.4.2
    pydotplus>=2.0.2
    pygam>=0.12.0
    pytorch-lightning>=2.4.0
    rich>=13.0.0
    scikit-learn>=1.7.0,<1.8.0
    scipy>=1.14.0
    seaborn>=0.13.0
    shap>=0.46.0
    statsmodels>=0.14.3
    torch>=2.5.0
python_requires = >=3.10
include_package_data = True
zip_safe = False

[options.entry_points]
console_scripts =
    causalexplain = causalexplain.__main__:main

[options.extras_require]
tests =
    pytest
    pytest-cov
full =
    dowhy>=0.14
docs =
    sphinx
    sphinx-gallery
    sphinx_rtd_theme
    numpydoc
    matplotlib
    roman
    myst-parser
    pydata-sphinx-theme
    sphinx-copybutton
    sphinx-design

[options.package_data]
* = *.txt, *.md, gui/static/*.css, gui/static/cytoscape/*.js

; [options.project_urls]
; Source Code = https://github.com/renero/causalexplain
; Documentation = https://github.com/renero/causalexplain/wiki
